# Generated by Django 2.2.8 on 2020-01-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='num_pos',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='number of open positions'),
        ),
    ]
