# Generated by Django 2.2.8 on 2020-05-07 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_job_num_pos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
    ]
